export const easyWords = {
  cor: [
    "Amarelo",
    "Anil",
    "Azul",
    "Bege",
    "Branco",
    "Bronze",
    "Caramelo",
    "Castanho",
    "Ciano",
    "Cinza",
    "Cobre",
    "Dourado",
    "Laranja",
    "Lilás",
    "Marrom",
    "Prata",
    "Preto",
    "Rosa",
    "Roxo",
    "Verde",
    "Vermelho",
    "Vinho",
    "Violeta",
  ],

  país: [
    "Alemanha",
    "Angola",
    "Argentina",
    "Bélgica",
    "Bolívia",
    "Brasil",
    "Camarões",
    "Canadá",
    "Catar",
    "Chile",
    "China",
    "Colômbia",
    "Croácia",
    "Cuba",
    "Dinamarca",
    "Egito",
    "Equador",
    "Espanha",
    "França",
    "Gana",
    "Grécia",
    "Holanda",
    "Índia",
    "Inglaterra",
    "Iraque",
    "Israel",
    "Itália",
    "Japão",
    "Marrocos",
    "México",
    "Noruega",
    "Paraguai",
    "Peru",
    "Polônia",
    "Portugal",
    "Rússia",
    "Salomão",
    "Sérvia",
    "Suécia",
    "Suíça",
    "Ucrânia",
    "Uruguai",
    "Venezuela",
    "Emirados Árabes Unidos",
  ],

  fruta: [
    "Abacate",
    "Abacaxi",
    "Açaí",
    "Acerola",
    "Amêndoa",
    "Amora",
    "Banana",
    "Cacau",
    "Caju",
    "Castanha",
    "Cereja",
    "Coco",
    "Goiaba",
    "Jaca",
    "Laranja",
    "Limão",
    "Maçã",
    "Mamão",
    "Manga",
    "Maracujá",
    "Melancia",
    "Melão",
    "Morango",
    "Pera",
    "Pêssego",
    "Pequi",
    "Uva",
  ],

  objeto: [
    "agulha",
    "algema",
    "alicate",
    "almofada",
    "anel",
    "antena",
    "anzol",
    "apagador",
    "armadura",
    "balde",
    "banco",
    "bandeira",
    "bengala",
    "bicicleta",
    "boia",
    "bola",
    "boneca",
    "borracha",
    "brinco",
    "cabide",
    "cadeado",
    "cadeira",
    "caderno",
    "caneca",
    "caneta",
    "capa",
    "celular",
    "colher",
    "copo",
    "dado",
    "dardo",
    "diamante",
    "diário",
    "escada",
    "escova",
    "espada",
    "esponja",
    "estátua",
    "faca",
    "fogão",
    "foice",
    "folha",
    "gaiola",
    "garfo",
    "garrafa",
    "gaveta",
    "geladeira",
    "giz",
    "grampo",
    "granada",
    "gravata",
    "iate",
    "ímã",
    "janela",
    "jaqueta",
    "jaula",
    "jeans",
    "lâmina",
    "lâmpada",
    "lanterna",
    "lápis",
    "lenço",
    "lençol",
    "lente",
    "livro",
    "lixa",
    "lixeira",
    "lona",
    "luva",
    "machado",
    "marreta",
    "máscara",
    "mochila",
    "panela",
    "papel",
    "peteca",
    "prato",
    "quadro",
    "régua",
    "revista",
    "rolha",
    "sabão",
    "saco",
    "sacola",
    "sandália",
    "sapato",
    "serra",
    "sofá",
    "tambor",
    "teclado",
    "telha",
    "tênis",
    "tesoura",
    "tigela",
    "tijolo",
    "varal",
    "vareta",
    "vassoura",
    "vela",
    "vidro",
    "volante",
  ],

  animal: [
    "abelha",
    "águia",
    "alce",
    "anta",
    "aranha",
    "arara",
    "avestruz",
    "bacalhau",
    "baleia",
    "barata",
    "boi",
    "borboleta",
    "burro",
    "cabra",
    "cachorro",
    "camelo",
    "canguru",
    "capivara",
    "cavalo",
    "cigarra",
    "cobra",
    "coelho",
    "coruja",
    "égua",
    "elefante",
    "foca",
    "formiga",
    "galinha",
    "galo",
    "gambá",
    "ganso",
    "gato",
    "gavião",
    "girafa",
    "gorila",
    "jacaré",
    "leão",
    "lobo",
    "macaco",
    "minhoca",
    "onça",
    "ovelha",
    "panda",
    "papagaio",
    "pássaro",
    "pato",
    "pavão",
    "peixe",
    "pinguim",
    "pombo",
    "porco",
    "quero quero",
    "raposa",
    "rato",
    "sapo",
    "tartaruga",
    "tatu",
    "tigre",
    "touro",
    "tubarão",
    "tucano",
    "urso",
    "urubu",
    "vaca",
    "zebra",
  ],
  cidade: [
    "Londres",
    "Singapura",
    "Paris",
    "Dubai",
    "Nova York",
    "Tóquio",
    "Roma",
    "Praga",
    "Meca",
    "Miami",
    "Amsterdam",
    "Los Angeles",
    "Las Vegas",
    "Barcelona",
    "Viena",
    "Cancun",
    "Berlim",
    "Veneza",
    "Madri",
    "Orlando",
    "Atenas",
    "Cairo",
    "Pequim",
    "Munique",
    "Lisboa",
    "Jerusalém",
    "São Francisco",
    "Cidade do México",
    "Buenos Aires",
    "Lima",
    "Santiago",
    "Rio de Janeiro",
    "Porto",
    "Gramado",
    "São Paulo",
    "Maceió",
    "Belo Horizonte",
    "Cuiabá",
    "Salvador",
    "Fortaleza",
    "Recife",
    "Natal",
    "Brasília",
  ],
  "estado brasileiro": [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
    "Distrito Federal",
  ],

  "área de atuação": [
    "Administração",
    "Gastronomia",
    "Hotelaria",
    "Segurança Pública",
    "Turismo",
    "Artes e Design",
    "Animação",
    "Arquitetura e Urbanismo",
    "Artes Visuais",
    "Dança",
    "Design",
    "Design de Games",
    "Design de Moda",
    "Fotografia",
    "Música",
    "Teatro",
    "Alimentos",
    "Astronomia",
    "Ciências Biológicas",
    "Ecologia",
    "Medicina Veterinária",
    "Ciência da Computação",
    "Computação",
    "Estatística",
    "Física",
    "Informática",
    "Matemática",
    "Química",
    "Arqueologia",
    "Ciências Humanas",
    "Direito",
    "Filosofia",
    "Geografia",
    "História",
    "Letras",
    "Libras",
    "Pedagogia",
    "Tradutor",
    "Jornalismo",
    "Publicidade",
    "Engenharia Aeronáutica",
    "Engenharia Agrícola",
    "Engenharia Civil",
    "Engenharia da Computação",
    "Engenharia de Alimentos",
    "Engenharia de Petróleo",
    "Engenharia de Produção",
    "Engenharia de Sistemas",
    "Engenharia Elétrica",
    "Engenharia Eletrônica",
    "Engenharia Física",
    "Engenharia Florestal",
    "Engenharia Mecânica",
    "Engenharia Química",
    "Mineração",
    "Biomedicina",
    "Educação Física",
    "Enfermagem",
    "Esporte",
    "Farmácia",
    "Fisioterapia",
    "Medicina",
    "Nutrição",
    "Odontologia",
    "Psicologia",
    "Radiologia",
  ],
  "parte do corpo": [
    "boca",
    "estômago",
    "intestino delgado",
    "intestino grosso",
    "laringe",
    "pulmões",
    "coração",
    "rins",
    "bexiga",
    "ovários",
    "útero",
    "pele",
    "cérebro",
    "Barriga",
    "Boca",
    "Bochecha",
    "Braço",
    "Cabeça",
    "Cabelo",
    "Canela",
    "Cintura",
    "Coxa",
    "Dedo Polegar",
    "Lábios",
    "Língua",
    "Mão",
    "Nariz",
    "Nuca",
    "Olhos",
    "Ouvido",
    "Pé",
    "Peito",
    "Perna",
    "Pés",
    "Rosto",
    "Testa",
    "Unha",
  ],
  "legume ou verdura": [
    "Abóbora",
    "Batata doce",
    "Ervilha",
    "Feijão",
    "Abobrinha",
    "Batata",
    "Cará",
    "Hortelã",
    "Orégano",
    "Aipim",
    "Batata doce",
    "Alho",
    "Palmito",
    "Erva doce",
    "Nabo",
    "Amêndoa",
    "Beterraba",
    "Amendoim",
    "Agrião",
    "Erva mate",
    "Quiabo",
    "Rabanete",
    "Quinoa",
    "Noz",
    "Pepino",
    "Salsa",
    "Mandioca",
    "Vagem",
    "Arroz",
    "Soja",
    "Pequi",
    "Cebola",
    "Pimenta",
    "Aveia",
    "Alface",
    "Pimentão",
    "Avelã",
    "Cenoura",
    "Couve",
    "Tomate",
    "Milho",
    "Azeitona",
    "Mogango",
    "Trigo",
  ],
  esporte: [
    "Atletismo",
    "Barra fixa",
    "Basquete",
    "Cabo de guerra",
    "Caminhada",
    "Capoeira",
    "Corrida",
    "Escalada",
    "Futebol",
    "Futsal",
    "Ginástica",
    "Golfe",
    "Nado artístico",
    "Natação",
    "Paraquedismo",
    "Pesca esportiva",
    "Peteca",
    "Queimada",
    "Rapel",
    "Salto com vara",
    "Salto em distância",
    "Sinuca",
    "Tênis",
    "Vela",
    "Voleibol",
    "Voleibol de praia",
    "Xadrez",
  ],
};

// -------------------------------------------------------------

export const hardWords = {
  cor: [
    "Açafrão",
    "Âmbar",
    "Amêndoa",
    "Ametista",
    "Cáqui",
    "Cinzento",
    "Damasco",
    "Índigo",
    "Lavanda",
    "Magenta",
    "Púrpura",
    "Sépia",
    "Rubro",
    "Turquesa",
  ],

  país: [
    "Afeganistão",
    "África do Sul",
    "Albânia",
    "Arábia Saudita",
    "Argélia",
    "Armênia",
    "Austrália",
    "Áustria",
    "Bulgária",
    "Coreia do Norte",
    "Coreia do Sul",
    "Finlândia",
    "Hungria",
    "Honduras",
    "Islândia",
    "Madagascar",
    "Malásia",
    "Nigéria",
    "Nova Zelândia",
    "Vietnã",
    "República Dominicana",
    "República Tcheca",
    "Taiwan",
    "Reino Unido",
  ],

  fruta: [
    "Ameixa",
    "Avelã",
    "Carambola",
    "Cupuaçu",
    "Damasco",
    "Framboesa",
    "Guaraná",
    "Graviola",
    "Jabuticaba",
    "Kiwi",
    "Romã",
    "Tangerina",
  ],

  objeto: [
    "abajur",
    "alfinete",
    "ampulheta",
    "binóculo",
    "canivete",
    "aspirador",
    "cinzeiro",
    "desodorante",
    "detergente",
    "sabonete",
    "serrote",
    "tapete",
    "vestido",
    "viseira",
    "apito",
    "apontador",
    "óculos",
    "calculadora",
    "computador",
    "etiqueta",
    "extintor",
    "foguete",
    "frigideira",
    "furadeira",
    "impressora",
    "capacete",
    "chicote",
    "chinelo",
    "colchão",
    "espelho",
    "flecha",
    "ingresso",
    "martelo",
    "raquete",
    "disco",
    "dominó",
    "âncora",
    "aquecedor",
    "bússola",
    "dentadura",
    "sapateira",
    "xadrez",
    "xícara",
    "skate",
    "spray",
    "telefone",
    "televisão",
    "torneira",
    "travesseiro",
    "troféu",
    "uniforme",
    "drone",
    "dicionário",
    "medalha",
    "microfone",
    "monitor",
    "mouse",
    "notebook",
    "parafuso",
    "pincel",
    "prateleira",
    "pulseira",
    "relógio",
    "retrovisor",
    "balança",
    "esmalte",
    "escudo",
    "envelope",
    "ferradura",
    "freezer",
    "guarda chuva",
    "guardanapo",
    "guilhotina",
    "isopor",
    "isqueiro",
    "lapiseira",
    "liquidificador",
    "helicóptero",
    "grampeador",
    "filmadora",
  ],

  animal: [
    "beija flor",
    "besouro",
    "bezerro",
    "bode",
    "búfalo",
    "camarão",
    "carrapato",
    "codorna",
    "crocodilo",
    "cupim",
    "escorpião",
    "estrela do mar",
    "falcão",
    "gafanhoto",
    "golfinho",
    "hipopótamo",
    "joaninha",
    "lagartixa",
    "lagosta",
    "leopardo",
    "lesma",
    "mico",
    "morcego",
    "mosca",
    "mosquito",
    "periquito",
    "pernilongo",
    "pica pau",
    "porco espinho",
    "preguiça",
    "tilápia",
  ],
  cidade: [
    "Hong Kong",
    "Bangkok",
    "Macau",
    "Shenzhen",
    "Istambul",
    "Mumbai",
    "Shanghai",
    "Seul",
    "Milão",
    "Toronto",
    "Florença",
    "Sydney",
    "Budapeste",
    "Punta Cana",
    "São Petersburgo",
    "Kyoto",
    "Bruxelas",
    "Vancouver",
    "Copenhague",
    "Varsóvia",
    "Marraquexe",
    "Porto de galinhas",
    "Aracaju",
    "Florianópolis",
    "Foz do Iguaçu",
    "Ouro Preto",
  ],
  "Área de atuação": [
    "Administração Pública",
    "Agropecuária",
    "Ciências Aeronáuticas",
    "Ciências Contábeis",
    "Ciências Econômicas",
    "Negócios Imobiliários",
    "Marketing",
    "Logística",
    "Design de Interiores",
    "Luteria",
    "Produção Fonográfica",
    "Produção Cênica",
    "Agroecologia",
    "Biotecnologia",
    "Ciências Agrárias",
    "Geofísica",
    "Geologia",
    "Meteorologia",
    "Zootecnia",
    "Redes de Computadores",
    "Segurança da Informação",
    "Sistemas de Informação",
    "Intérprete",
    "Biblioteconomia",
    "Quiropraxia",
    "Obstetrícia",
    "Fonoaudiologia",
    "Mecatrônica Industrial",
    "Engenharia de Software",
    "Engenharia Biomédica",
    "Automação Industrial",
    "Teologia",
    "Construção Civil",
    "Construção Naval",
    "Engenharia Mecatrônica",
    "Engenharia Metalúrgica",
    "Nanotecnologia",
    "Linguística",
    "Eletrônica Industrial",
    "Eletrotécnica Industrial",
    "Engenharia Acústica",
    "Engenharia Naval",
    "Engenharia Nuclear",
    "Ciências Sociais",
    "Produção de Bebidas",
    "Agronomia",
  ],
  "parte do corpo": [
    "faringe",
    "esôfago",
    "vasos sanguíneos",
    "medula espinhal",
    "Antebraço",
    "Axila",
    "Calcanhar",
    "Cílio",
    "Cotovelo",
    "Costas",
    "Dedo Anelar",
    "Dedos dos pés",
    "Dedo Indicador",
    "Dedo Médio",
    "Dedo Mínimo",
    "Joelho",
    "Pálpebra",
    "Panturrilha",
    "Sobrancelha",
    "Quadril",
    "Nádegas",
    "Tornozelo",
    "Tronco",
    "Umbigo",
    "Ombro",
    "Seio",
    "Pescoço",
    "Pulso",
    "Queixo",
  ],
  "legume ou verdura": [
    "Fava",
    "Gengibre",
    "Gergelim",
    "Inhame",
    "Oliva",
    "Açafrão",
    "Lentilha",
    "Castanha de caju",
    "Berinjela",
    "Grão de bico",
    "Castanha do pará",
    "Alcachofra",
    "Brócolis",
    "Espinafre",
    "Manjericão",
    "Repolho",
    "Louro",
    "Alcaparra",
    "Taioba",
    "Rúcula",
    "Cebolinha",
    "Malagueta",
    "Maxixe",
    "Mostarda",
    "Tomilho",
    "Pistache",
    "Alho poró",
    "Aspargo",
    "Chia",
    "Couve flor",
    "Chuchu",
    "Almeirão",
    "Alecrim",
    "Linhaça",
    "Jiló",
    "Coentro",
  ],
  esporte: [
    "Arco e flecha",
    "Polo",
    "Rugby",
    "Argolas",
    "Arremesso de peso",
    "Asa delta",
    "Automobilismo",
    "Bilhar",
    "Boliche",
    "Boxe",
    "Ciclismo",
    "Esgrima",
    "Esqui aquático",
    "Futebol americano",
    "Futevôlei",
    "Ginástica artística",
    "Ginástica olímpica",
    "Handebol",
    "Hóquei",
    "Judô",
    "Karatê",
    "Kart",
    "Nado sincornizado",
    "Patinação",
    "Pôquer",
    "Queda de braço",
    "Rugby",
    "Skate",
    "Sumô",
    "Surfe",
    "UFC",
    "Trampolim",
    "Zumba",
    "Remo",
    "Polo aquático",
    "Motociclismo",
    "Canoagem",
    "Dardos",
    "Trapézio",
  ],
};

// -----------------------------------
