export const easyWords = {
  cor: [
    "Amarelo",
    "Anil",
    "Azul",
    "Bege",
    "Branco",
    "Caramelo",
    "Castanho",
    "Ciano",
    "Cinza",
    "Cobre",
    "Dourado",
    "Laranja",
    "Lilás",
    "Marrom",
    "Prata",
    "Preto",
    "Rosa",
    "Roxo",
    "Verde",
    "Vermelho",
    "Vinho",
    "Violeta",
  ],

  país: [
    "Alemanha",
    "Angola",
    "Argentina",
    "Bélgica",
    "Bolívia",
    "Brasil",
    "Camarões",
    "Canadá",
    "Chile",
    "China",
    "Colômbia",
    "Croácia",
    "Cuba",
    "Dinamarca",
    "Egito",
    "Equador",
    "Espanha",
    "França",
    "Gana",
    "Grécia",
    "Holanda",
    "Índia",
    "Inglaterra",
    "Iraque",
    "Israel",
    "Itália",
    "Japão",
    "Marrocos",
    "México",
    "Noruega",
    "Paraguai",
    "Peru",
    "Polônia",
    "Portugal",
    "Rússia",
    "Sérvia",
    "Suécia",
    "Suíça",
    "Ucrânia",
    "Uruguai",
    "Venezuela",
  ],

  fruta: [
    "Abacate",
    "Abacaxi",
    "Açaí",
    "Acerola",
    "Amêndoa",
    "Amora",
    "Banana",
    "Cacau",
    "Caju",
    "Castanha",
    "Cereja",
    "Coco",
    "Goiaba",
    "Jaca",
    "Laranja",
    "Limão",
    "Maçã",
    "Mamão",
    "Manga",
    "Maracujá",
    "Melancia",
    "Melão",
    "Morango",
    "Pera",
    "Pêssego",
    "Pequi",
    "Uva",
  ],

  objeto: [
    "agulha",
    "algema",
    "alicate",
    "almofada",
    "anel",
    "antena",
    "anzol",
    "apagador",
    "armadura",
    "balde",
    "banco",
    "bandeira",
    "bengala",
    "bicicleta",
    "boia",
    "bola",
    "boneca",
    "borracha",
    "brinco",
    "cabide",
    "cadeado",
    "cadeira",
    "caderno",
    "caneca",
    "caneta",
    "capa",
    "celular",
    "colher",
    "copo",
    "dado",
    "dardo",
    "diamante",
    "diário",
    "escada",
    "escova",
    "espada",
    "esponja",
    "estátua",
    "faca",
    "fogão",
    "foice",
    "folha",
    "gaiola",
    "garfo",
    "garrafa",
    "gaveta",
    "geladeira",
    "giz",
    "grampo",
    "granada",
    "gravata",
    "iate",
    "ímã",
    "janela",
    "jaqueta",
    "jaula",
    "lâmina",
    "lâmpada",
    "lanterna",
    "lápis",
    "lenço",
    "lençol",
    "lente",
    "livro",
    "lixa",
    "lixeira",
    "lona",
    "luva",
    "machado",
    "marreta",
    "máscara",
    "mochila",
    "panela",
    "papel",
    "peteca",
    "prato",
    "quadro",
    "régua",
    "revista",
    "rolha",
    "sabão",
    "saco",
    "sacola",
    "sandália",
    "sapato",
    "serra",
    "sofá",
    "tambor",
    "teclado",
    "telha",
    "tênis",
    "tesoura",
    "tigela",
    "tijolo",
    "vareta",
    "vassoura",
    "vela",
    "vidro",
    "volante",
  ],

  animal: [
    "abelha",
    "águia",
    "alce",
    "anta",
    "aranha",
    "arara",
    "avestruz",
    "bacalhau",
    "baleia",
    "barata",
    "boi",
    "borboleta",
    "burro",
    "cabra",
    "cachorro",
    "camelo",
    "canguru",
    "capivara",
    "cavalo",
    "cigarra",
    "cobra",
    "coelho",
    "coruja",
    "égua",
    "elefante",
    "foca",
    "formiga",
    "galinha",
    "galo",
    "gambá",
    "ganso",
    "gato",
    "gavião",
    "girafa",
    "gorila",
    "jacaré",
    "leão",
    "lobo",
    "macaco",
    "minhoca",
    "onça",
    "ovelha",
    "panda",
    "papagaio",
    "pássaro",
    "pato",
    "pavão",
    "peixe",
    "pinguim",
    "pombo",
    "porco",
    "quero quero",
    "raposa",
    "rato",
    "sapo",
    "tartaruga",
    "tatu",
    "tigre",
    "touro",
    "tubarão",
    "tucano",
    "urso",
    "urubu",
    "vaca",
    "zebra",
  ],
  cidade: [
    "Londres",
    "Paris",
    "Nova York",
    "Tóquio",
    "Las Vegas",
    "Rio de Janeiro",
    "São Paulo",
    "Maceió",
    "Belo Horizonte",
    "Cuiabá",
    "Salvador",
    "Fortaleza",
    "Recife",
    "Natal",
    "Brasília",
  ],
  "estado brasileiro": [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
    "Distrito Federal",
  ],
  "parte do corpo": [
    "boca",
    "estômago",
    "intestino delgado",
    "intestino grosso",
    "laringe",
    "pulmões",
    "coração",
    "rins",
    "bexiga",
    "ovários",
    "útero",
    "pele",
    "cérebro",
    "Barriga",
    "Boca",
    "Bochecha",
    "Braço",
    "Cabeça",
    "Cabelo",
    "Canela",
    "Cintura",
    "Coxa",
    "Dedo Polegar",
    "Lábios",
    "Língua",
    "Mão",
    "Nariz",
    "Nuca",
    "Olhos",
    "Ouvido",
    "Pé",
    "Peito",
    "Perna",
    "Pés",
    "Rosto",
    "Testa",
    "Unha",
  ],
  "legume ou verdura": [
    "Abóbora",
    "Batata doce",
    "Ervilha",
    "Feijão",
    "Abobrinha",
    "Batata",
    "Cará",
    "Hortelã",
    "Orégano",
    "Aipim",
    "Batata doce",
    "Alho",
    "Palmito",
    "Erva doce",
    "Amêndoa",
    "Beterraba",
    "Amendoim",
    "Erva mate",
    "Quiabo",
    "Rabanete",
    "Quinoa",
    "Noz",
    "Pepino",
    "Salsa",
    "Mandioca",
    "Vagem",
    "Arroz",
    "Soja",
    "Pequi",
    "Cebola",
    "Pimenta",
    "Aveia",
    "Alface",
    "Pimentão",
    "Avelã",
    "Cenoura",
    "Couve",
    "Tomate",
    "Milho",
    "Azeitona",
    "Mogango",
    "Trigo",
  ],
  esporte: [
    "Atletismo",
    "Barra fixa",
    "Basquete",
    "Caminhada",
    "Corrida",
    "Escalada",
    "Futebol",
    "Futsal",
    "Ginástica",
    "Golfe",
    "Nado artístico",
    "Natação",
    "Paraquedismo",
    "Pesca esportiva",
    "Peteca",
    "Queimada",
    "Rapel",
    "Salto com vara",
    "Salto em distância",
    "Tênis",
    "Voleibol",
    "Voleibol de praia",
  ],
};

// -------------------------------------------------------------

export const hardWords = {
  cor: [
    "Cáqui",
    "Damasco",
    "Índigo",
    "Lavanda",
    "Magenta",
    "Púrpura",
    "Turquesa",
  ],

  país: [
    "Afeganistão",
    "África do Sul",
    "Arábia Saudita",
    "Argélia",
    "Austrália",
    "Áustria",
    "Coreia do Norte",
    "Coreia do Sul",
    "Honduras",
    "Islândia",
    "Madagascar",
    "Nigéria",
    "Nova Zelândia",
    "Reino Unido",
  ],

  fruta: [
    "Ameixa",
    "Avelã",
    "Carambola",
    "Cupuaçu",
    "Damasco",
    "Framboesa",
    "Guaraná",
    "Graviola",
    "Jabuticaba",
    "Kiwi",
    "Romã",
    "Tangerina",
  ],

  objeto: [
    "abajur",
    "alfinete",
    "ampulheta",
    "binóculo",
    "canivete",
    "aspirador",
    "cinzeiro",
    "desodorante",
    "detergente",
    "sabonete",
    "serrote",
    "tapete",
    "vestido",
    "viseira",
    "apito",
    "apontador",
    "óculos",
    "calculadora",
    "computador",
    "etiqueta",
    "extintor",
    "foguete",
    "frigideira",
    "furadeira",
    "impressora",
    "capacete",
    "chicote",
    "chinelo",
    "colchão",
    "espelho",
    "flecha",
    "martelo",
    "raquete",
    "disco",
    "dominó",
    "âncora",
    "aquecedor",
    "bússola",
    "dentadura",
    "sapateira",
    "xícara",
    "skate",
    "spray",
    "telefone",
    "televisão",
    "torneira",
    "travesseiro",
    "troféu",
    "uniforme",
    "drone",
    "dicionário",
    "medalha",
    "microfone",
    "monitor",
    "mouse",
    "notebook",
    "parafuso",
    "pincel",
    "prateleira",
    "pulseira",
    "relógio",
    "retrovisor",
    "balança",
    "esmalte",
    "escudo",
    "envelope",
    "ferradura",
    "freezer",
    "guarda chuva",
    "guardanapo",
    "guilhotina",
    "isopor",
    "isqueiro",
    "lapiseira",
    "liquidificador",
    "helicóptero",
    "grampeador",
    "filmadora",
  ],

  animal: [
    "beija flor",
    "besouro",
    "bezerro",
    "bode",
    "búfalo",
    "camarão",
    "carrapato",
    "codorna",
    "crocodilo",
    "cupim",
    "escorpião",
    "estrela do mar",
    "falcão",
    "gafanhoto",
    "golfinho",
    "hipopótamo",
    "joaninha",
    "lagartixa",
    "lagosta",
    "leopardo",
    "lesma",
    "mico",
    "morcego",
    "mosca",
    "mosquito",
    "periquito",
    "pernilongo",
    "pica pau",
    "porco espinho",
    "preguiça",
    "tilápia",
  ],
  cidade: ["Aracaju", "Florianópolis", "Foz do Iguaçu", "Ouro Preto"],
  "parte do corpo": [
    "faringe",
    "esôfago",
    "vasos sanguíneos",
    "Antebraço",
    "Axila",
    "Calcanhar",
    "Cílios",
    "Cotovelo",
    "Costas",
    "Dedo Anelar",
    "Dedos dos pés",
    "Dedo Indicador",
    "Dedo Médio",
    "Dedo Mínimo",
    "Joelho",
    "Pálpebra",
    "Panturrilha",
    "Sobrancelha",
    "Quadril",
    "Nádegas",
    "Tornozelo",
    "Tronco",
    "Umbigo",
    "Ombro",
    "Seio",
    "Pescoço",
    "Pulso",
    "Queixo",
  ],
  "legume ou verdura": [
    "Gengibre",
    "Gergelim",
    "Inhame",
    "Açafrão",
    "Lentilha",
    "Castanha de caju",
    "Berinjela",
    "Grão de bico",
    "Castanha do pará",
    "Brócolis",
    "Espinafre",
    "Manjericão",
    "Repolho",
    "Louro",
    "Alcaparra",
    "Taioba",
    "Rúcula",
    "Cebolinha",
    "Maxixe",
    "Mostarda",
    "Tomilho",
    "Pistache",
    "Alho poró",
    "Aspargo",
    "Chia",
    "Couve flor",
    "Chuchu",
    "Almeirão",
    "Alecrim",
    "Linhaça",
    "Jiló",
    "Coentro",
  ],
  esporte: [
    "Arco e flecha",
    "Argolas",
    "Arremesso de peso",
    "Boxe",
    "Ciclismo",
    "Esgrima",
    "Futebol americano",
    "Futevôlei",
    "Ginástica artística",
    "Ginástica olímpica",
    "Handebol",
    "Judô",
    "Karatê",
    "Nado sincornizado",
    "Sumô",
    "Surfe",
    "Remo",
    "Polo aquático",
    "Canoagem",
  ],
};

// -----------------------------------
